
name: timbangan_ayam_kandang_rizki
description: Aplikasi OCR untuk timbangan ayam kandang
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.10.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
